# Generated by Django 4.1.7 on 2023-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('blogTopics', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Weather',
            },
        ),
    ]
